export const COUNTER_INCRIMENT = 'COUNTER_INCRIMENT';
export const COUNTER_DECRIMENT = 'COUNTER_DECRIMENT';

export const SET_CATEGORIES = 'SET_CATEGORIES';
export const SET_SUBCATEGORIES = 'SET_SUBCATEGORIES';
export const SET_FILTERED_DATA = 'SET_FILTERED_DATA';

export const SET_SLIDER_ITEMS = 'SET_SLIDER_ITEMS';
export const SET_PRODUCTS_FEATURED = 'SET_PRODUCTS_FEATURED';
export const SET_PRODUCTS_DISCOUNTED = 'SET_PRODUCTS_DISCOUNTED';
export const SET_PRODUCT_ITEM = 'SET_PRODUCT_ITEM';
export const SET_PRODUCT_SIMILAR_ITEMS = 'SET_PRODUCT_SIMILAR_ITEMS';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

export const ACCOUNT_ORDERS = 'ACCOUNT_ORDERS';
export const ACCOUNT_WISHLIST = 'ACCOUNT_WISHLIST';
export const ACCOUNT_WISHLIST_REMOVE_ITEM = 'ACCOUNT_WISHLIST_REMOVE_ITEM';
